#!/bin/bash
mariadb -u root -p"${MARIADB_ROOT_PASSWORD}" <<-EOSQL
    CREATE USER IF NOT EXISTS '${MARIADB_USER}-test'@'%' IDENTIFIED BY '123456';
    CREATE DATABASE IF NOT EXISTS \`${MARIADB_DATABASE}-test\`;
    GRANT ALL PRIVILEGES ON \`${MARIADB_DATABASE}-test\`.* TO '${MARIADB_USER}-test'@'%';
    FLUSH PRIVILEGES;
EOSQL
