x-logging: &_logging
    logging:
        driver: syslog
        options:
            syslog-address: ${SYSLOG_ADDR:-udp://localhost:514}
            syslog-format: "rfc5424micro"
            env: ${APP_ENV:-local}
            labels: ${APP_ENV:-local}
            tag: "{{.ImageName}}|{{.Name}}|{{.ID}}|${APP_ENV:-local}"

services:
    nginx:
        <<: [ *_logging ]
        deploy:
            mode: global
            resources:
                limits:
                    cpus: "2"
                    memory: "128M"

    php-fpm:
        <<: [ *_logging ]
        deploy:
            mode: global
            resources:
                limits:
                    cpus: "2"
                    memory: "512M"

    mariadb:
        <<: [ *_logging ]
        deploy:
            mode: global
            resources:
                limits:
                    cpus: "2"
                    memory: "2G"

    keydb:
        <<: [ *_logging ]
        deploy:
            mode: global
            resources:
                limits:
                    cpus: "1"
                    memory: "512M"

    libreoffice:
        <<: [ *_logging ]
        deploy:
            mode: global
            resources:
                limits:
                    cpus: "2"
                    memory: "1G"

    worker-libreoffice:
        <<: [ *_logging ]
        deploy:
            mode: global
            resources:
                limits:
                    cpus: "2"
                    memory: "1G"

    worker-ffmpeg:
        <<: [ *_logging ]
        deploy:
            mode: global
            resources:
                limits:
                    cpus: "2"
                    memory: "1G"

    worker-image:
        <<: [ *_logging ]
        deploy:
            mode: global
            resources:
                limits:
                    cpus: "2"
                    memory: "1G"

    worker-ai:
        <<: [ *_logging ]
        deploy:
            mode: global
            resources:
                limits:
                    cpus: "4"
                    memory: "4G"

    worker-data:
        <<: [ *_logging ]
        deploy:
            mode: global
            resources:
                limits:
                    cpus: "1"
                    memory: "512M"
