parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Service\Auth\TelegramAuthService:
        arguments:
            $telegramBotToken: '%env(TELEGRAM_BOT_TOKEN)%'

    App\Service\Conversion\ConversionManager:
        arguments:
            $shareDir: '%env(SHARE_DIR)%'

    App\Service\Queue\RedisConnectionFactory:
        arguments:
            $dsn: '%env(REDIS_DSN)%'

    AsyncAws\S3\S3Client:
        arguments:
            $configuration:
                endpoint: '%env(S3_ENDPOINT)%'
                accessKeyId: '%env(S3_KEY)%'
                accessKeySecret: '%env(S3_SECRET)%'
                region: '%env(S3_REGION)%'
                pathStyleEndpoint: '%env(bool:S3_USE_PATH_STYLE)%'

    App\Service\Storage\S3Storage:
        arguments:
            $bucketPrefix: '%env(S3_BUCKET_PREFIX)%'

    App\Service\Queue\ConversionResultPersister:
        arguments:
            $resultsBucket: '%env(S3_BUCKET_PREFIX)%-results'
