
services:
    metrics-exporter:
        deploy:
            mode: global
            resources:
                limits:
                    cpus: "0.1"
                    memory: "64M"

    php:
        deploy:
            mode: global
            resources:
                limits:
                    cpus: "1"
                    memory: "512M"

    cron:
        deploy:
            mode: global
            resources:
                limits:
                    cpus: "2"
                    memory: "1G"

    mariadb:
        deploy:
            mode: global
            resources:
                limits:
                    cpus: "2"
                    memory: "3G"

    nginx:
        # Prometheus 7d peak (matrix_dev): mem 19M, cpu 0.004
        mem_limit: "128M"
        cpus: "1.0"
