user  nginx;
worker_processes  auto;

error_log syslog:server=gl.xakki.ru:45102,tag=lib warn;
pid        /var/run/nginx.pid;


events {
    worker_connections  1024;
}


http {
    include       mime.types;
    default_type  application/octet-stream;


    access_log off;
    include  params/cache_params;
    include  params/http_params;

    include conf.d/*.conf;
}

